d /run/shiden-guardian 0711 root root -
d /run/shiden-guardian/observe 2770 shiden-guardian shiden-guardian-observe -
d /run/shiden-guardian/control 2770 shiden-guardian shiden-guardian-control -
d /run/shiden-guardian/smtp 2770 shiden-guardian shiden-guardian-control -
